# Configuration file for data-driven forecasting
# Set required data paths - these are relative paths to where this script is stored

# Domain, note that the name needs to match the data paths that follow - current options are: "05BB001" for the Bow River at Banff in Alberta, Canada, or "09081600" for the Crystal River Above Avalanche Creek, Near Redstone in Colorado, USA

domain: "V1021"

# Observational data path
#streamflow_obs_path: "../CH_data/CH_input_data/Qobs_Camels.nc"
#precip_obs_path: "../CH_data/CH_input_data/P_data.nc"
#SWE_obs_path: "../CH_data/CH_input_data/SWE_data.nc"

# GIS data paths
#basins_shp_path: "../CH_data/CH_input_data/nival_basins.shp"
#basins_dem_path: "../test_case_data/input_data/MERIT_Hydro_dem_"

# Output data paths
#plots_path: "../CH_data/CH_output_plots/"
#output_data_path: "../CH_data/CH_output_data/"

#Camels Schweiz
streamflow_obs_path: "../PREVAH/input_data/Q_prevah.nc"
precip_obs_path: "../PREVAH/input_data/P_prevah.nc" # camels
SWE_obs_path: "../PREVAH/input_data/SWE_prevah.nc" # camels
basins_shp_path: "../PREVAH/input_data/ebene_40km_with_ids.shp"
basins_dem_path: "../PREVAH/input_data/MERIT_Hydro_dem_"
plots_path: "../PREVAH/output_plots/" # camels
output_data_path: "../PREVAH/output_data/" # camels

